### ISSUE TITLE
Broken API for listing agents

### ISSUE THREAD

**Issue by Bakacolak** [wazuh/wazuh-splunk#1071]
Hello, 
I can't list agents from wazuh app : 
LOG : 
2021/04/15 16:14:59 | ERROR | api: Error making API request: {
2021/04/15 16:14:59 | ERROR | api: Error while requesting to Wazuh API: {

I tried with upgrade from 3.13 wazuh and 8.0.4 splunk version to 4.1.4 and 8.1.2 and from fresh install in last version (with wazuh APP wazuh_splunk-4.1.4_8.1.2-1.tar.gz) --> same result

The API is connected.
edit: i have agents connected, i got logs and can export as csv the list.

![image](https://user-images.githubusercontent.com/11148432/114884265-ed686900-9e05-11eb-8283-8e11f7d26e19.png)

Thks for the works

**Comment by Desvelao** [comment]
Hi @Bakacolak ,

I think the problem is related to the browser cache (related to the files) that is using the files from the previous Wazuh app version you had (3.13.x_8.0.4) instead of the new ones (4.1.4_8.1.2).

Could you clear the browser cache and try again?

You could try in an incognito window or another browser to check this.

**Comment by frankeros** [comment]
Hi @Bakacolak, do you still have the problem?

**Comment by Bakacolak** [comment]
Hey,
i just tryed in incognito, it work, you were right,
Thanks for answers!!
