### ISSUE TITLE
Multiple Standalone Manager API Connection Issues

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh-splunk#1106]
| Wazuh | Splunk |
| ----- | ------- |
| 4.1.5 | 8.0.3 |

**Description**
I have multiple Wazuh 4.1.5 Managers and when I try to add more than one manager to the Wazuh API Configuration it comes up with an error in the bottom right that just says ! 'data' 

If I remove one manager and then add a new one it works on the new one, but can't add a second one again.

When I check api.log on the wazuh manager it just shows:
INFO: unknown_user ***IP*** "GET /" with parameters {} and body {} done in 0.002s: 401

Seems to be an issue with authentication to a second standalone manager in the list.

**Steps to reproduce**
1. Go to Wazuh Splunk App (Settings)
2. Add a manager
3. Attempt to add a second manager

**Comment by mpRegalado** [comment]
Hello! Thank you for reaching out to us! Apologies for the late reply
We have addressed this issue in [this pull request](https://github.com/wazuh/wazuh-splunk/pull/1136) and you will be able to find it on our latest releases!
You may want to update your wazuh installation in order to make use of the latest fixes and features, you can find information on how to do so [in our documentation](https://documentation.wazuh.com/current/upgrade-guide/index.html)

I hope it helps!
