### ISSUE TITLE
Implement Management Section (users, policies, role mapping).

### ISSUE THREAD

**Issue by eze9252** [wazuh/wazuh-splunk#1148]
|Wazuh| Splunk | Epic | 
| --- | --- | --- |
| 4.2.x| 8.1.4 / 8.2.2 | #389  |

In order to keep it consistent with Wazuh's Kibana App, I think it would be better to add a new section with the only responsability of managing RBAC. This means a new section on the navigation bar named "_Security_", with a secondary navigation bar in it (as in Kibana) to toggle between **Users, Roles, Policies and Roles mapping**. Each of this sections will contain a table as in Kibana.

Proposed Splunk's RBAC
_Note: ignore the icon, it's just a fast mockup_
![image](https://user-images.githubusercontent.com/15186973/135825945-4f061630-f62d-4c3b-9d44-f45d2be2e73a.png)

As a result, new views and controllers would be created leaving the rest untouched (for now), providing a cleaner and easier approach in terms of implementation.

**Comment by AlexRuiz7** [comment]
This [PR #1157 ](https://github.com/wazuh/wazuh-splunk/pull/1157) moves every resolver related to RBAC to a separated files.

Check it out and approve the merge if you think that's fine

**Comment by AlexRuiz7** [comment]
## Some bugs

- [ ] Last reserved policy show action buttons. It shouldn't
![image](https://user-images.githubusercontent.com/15186973/144047513-7c449347-05e4-45c4-be23-2c614e400751.png)

- [ ] Role Mapping does not save the selected roles 
- [ ] Reserved `wui_opendistro_admin` does not show the related rule. Also, the JSON editor does not show the rule correctly, shows `username` instead of `user_name`.

![image](https://user-images.githubusercontent.com/15186973/144047869-989a954a-d54b-4d74-9994-c48a82568924.png)

**Comment by Desvelao** [comment]
### Bugs
- [ ] Disabled button when try to edit a role
![image](https://user-images.githubusercontent.com/34042064/144208945-e3645592-a5eb-4c3b-998f-93ec8d7d5d0f.png)

- [ ] Can't edit a policy
![image](https://user-images.githubusercontent.com/34042064/144208753-31a7a044-c1c1-45d3-b5a1-c6242fd0b12a.png)
