### ISSUE TITLE
Wazuh App for Splunk not compatible with the Splunk Cloud

### ISSUE THREAD

**Issue by jpcordone** [wazuh/wazuh-splunk#1273]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2.5 | Cloud  | 

**Description**
The Wazuh App for Splunk is not compatible with the Splunk Cloud.

**Steps to reproduce**
As per Splunk's [website](https://splunkbase.splunk.com/app/3688/) the latest version of the Wazuh App that is compatible with Splunk Cloud is 3.13.1
The latest version of the Wazuh App for Splunk should be compatible with Splunk Cloud to keep the same features and version used with Splunk Enterprise.

**Additional context**
Issue #1086 had already tackled this bug before. Even though #1099 closed the issue, it seems the application is still not compatible. Issue #1116 mentions tests for Splunk on different environments, it does not mention any Splunk Cloud specific testing

**Comment by AlexRuiz7** [comment]
With the inclusion of the PR #1270, the remaining failing checks reported by the [Splunk AppInspect Tool](https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/useappinspectclitool/) are:

- [  F  ] - check_that_local_does_not_exist - Check that the 'local' directory does not exist. All configuration should be in the 'default' directory. 
- [  F  ] - check_for_local_meta - Check that the file 'local.meta' does not exist. All metadata permissions should be set in 'default.meta'.

**Comment by AlexRuiz7** [comment]
Update
--------
The checks above where failing due to some autogenerated / leftover files that do not exist on our packages.

All checks now pass without failures:

```
SplunkAppForWazuh Report Summary:

         error:  0
       failure:  0
       skipped:  0
  manual_check: 15
not_applicable: 47
       warning:  6
       success: 132
-------------------
         Total: 200
```

Please, close this is issue if you see fit @jpcordone.

**Comment by AlexRuiz7** [comment]
## Update: incompatibility with Splunk Cloud

Although the Report Summary provided by Splunk contains no failures, as seen on the previous post, the Cloud compatibility has been refused due to some failed checks for the Victoria and Classic Cloud Experience of Splunk.

The nature of this checks and the reason why they fail are unknown, as the only feedback provided is the one seen above.

We must study and investigate this further, by carefully reading their documentation, blogs and recommendations for Splunk Cloud compatibilty, and eventually even getting in touch with Splunk.

![image](https://user-images.githubusercontent.com/15186973/156768411-87ad4ad6-8858-4f0a-9638-234aaf7aa231.png)

**Comment by gdiazlo** [comment]
The support of Splunk cloud might be revisited. Closing this issue as it is not a priority.
