### ISSUE TITLE
Consider compatibility between Wazuh App and Splunk 8.2.5

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-splunk#1298]
Hello Team,
I need you to consider developing a Wazuh App for Splunk compatible with Splunk 8.2.5.
More specifically because this version of Splunk has deprecated the HTML dashboards and it is recommending using Dashboard Studio for them.
![image](https://user-images.githubusercontent.com/37050249/160425776-ee80362f-f208-43e0-a582-d781205e9229.png)

I hope you can help me with this.

**Comment by schadom** [comment]
I tried to install Wazuh App for Splunk v4.2.6 with Splunk 8.2.5 but I get a blank screen because of mixed content blocking. It seems that some of the asset URLs within the app are constructed absolute (with http://) instead of relative.

I have an nginx tls reverse proxy in front of my Splunk instance. Since all other apps (except the Wazuh App for Splunk) are working as expected, I assume it must be an issue within the apps code:

![SplunkAppForWazuh_mixed_content](https://user-images.githubusercontent.com/33547308/161357973-93dce8e9-69f0-4594-9be6-24cad6493433.png)

**Comment by AlexRuiz7** [comment]
@dariommr I'm closing this issue as the latest App version (`4.3.0`) is compatible with Splunk `8.1.x` and `8.2.x`.
On another note, the warning about deprecrated HTML is and will still showing up on `8.2.x`. To remove that warning we'd need to re-implement the App using the Dashboard Studio, and that's not going to happen as we are pregressively abandoning the support for Splunk. Furthermore, by the looks of the warning, Splunk will stop providing support for legacy Apps soon.

@schadom You could try using the recently released `4.3.0` version and check if it works. If the problem persists please open a new issue using the `Bug Report` template and the `community` tag.
