### ISSUE TITLE
Splunk App reporting Unexpected version

### ISSUE THREAD

**Issue by weekendwarrior1999** [wazuh/wazuh-splunk#1339]
New Universal Forwarder with wazuh manager installed on Rocky Linux
On the indexer (8.2.6) I've installed the props,indexes and inputs conf files and the forwarder is being seen by the indexer.(Not that has anything do do with the issue)

After installing "Wazuh app for Splunk 8.2.6" revision 8166 and attempting to input the API settings  using the default u:p as instructed in the instructions, I receive an error "Cannot save the API: Cannot connect to the API, please check the App logs"

Clicking on the "Logs" tab within the Splunk App on the Indexer, I find these entries:

```
ERROR | manager: Cannot connect to API : Unexpected Wazuh version. App version: 2.3.4, API version: 4.3.4
ERROR | Error checking the Wazuh API version: Unexpected Wazuh version. App version: 2.3.4, API version: 4.3.4
ERROR | manager: Cannot connect to API :
ERROR | Error checking the Wazuh API version:
ERROR | Wazuh_API:
wazuh-token: error on get_auth_token:
```

On the Universal Forwarder / Wazuh manager machine, looking at the api.log entries, I see these entries associated with the connection attempt.

`INFO: wazuh <Indexer IP>"GET /" with parameters {} and body {} done in 0.023s: 200`

If on the indexer I run:

`curl -k -X GET "https://<forwarder ip>:55000/" -H "Authorization: Bearer $(curl -u wazuh:wazuh -k -X GET 'https://<forwarder ip>:55000/security/user/authenticate?raw=true')"`

I get the return:
`{"data": {"title": "Wazuh API REST", "api_version": "4.3.4", "revision": 40316, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/4.3/LICENSE", "hostname": "wazuh", "timestamp": "2022-06-09T15:53:57Z"}, "error": 0}`

**Comment by weekendwarrior1999** [comment]
Removed the app
Restarted splunk
installed the app from link above
restarted splunk
Issue persisted
cleared cache in browser
tried, Chrome, Safari, Firefox
rebooted my local machine
Issue persists

Still see the same as above and getting this notification:
![Screen Shot 2022-06-09 at 2 34 40 PM](https://user-images.githubusercontent.com/14844160/172923576-49b36f96-6ad8-498d-b39a-c38f938afa85.png)

**Comment by weekendwarrior1999** [comment]
Attempted in a Chrome "Incognito browser/session" also. It showed the same Warning as above also...

**Comment by weekendwarrior1999** [comment]
So after some additional investigating, I realized the Wazuh App was reporting the same version number as that of the installed "Suricata App". After removing this app, the Wazuh App then began reporting the version as 3.41.0, which is the same version number as "ES Content Updates" app that is installed.

I even tried reverting back to Splunk 8.2.3.2 (just upgraded to 8.2.6 yesterday) and nothing changed.

**Comment by AlexRuiz7** [comment]
Hello again @weekendwarrior1999 

Thank you for the effort, the patience and the time invested to investigate this issue. 

The information you provided has been greatly interesting and helpful, as I could find more information about this problem in the Splunk community. There have been several users affected by this on other Apps or plugins, as can be seen here:

- https://community.splunk.com/t5/Developing-for-Splunk-Enterprise/Reading-conf-files-in-TA/m-p/542141
- https://community.splunk.com/t5/Getting-Data-In/Splunk-is-pulling-the-wrong-custom-conf-file/m-p/407841

Fortunately, I could also find a post with a solution :) :
- https://community.splunk.com/t5/Splunk-Search/How-can-I-retrieve-a-value-from-local-conf-file-and-use-it/m-p/49243#M11788

I confirm then that this is a bug on our side, as we do not explicitly provide to the Splunk CLI the path of our configuration files, so it looks for the queried configuration on other Apps, returning the first one that matches.

I'll start working on this now, and I'll share a custom package with you when it's ready (in a few hours), so you can start using our App as soon as possible.

Once the fix is validated, we'll include it on the next patch release.

Again, many thanks for your valuable research.

Standby as I work on the fix.
Regards,
Alex.

**Comment by AlexRuiz7** [comment]
# Research


## Occurrences of `cli.getConfStanza()`

On revision `4307`, the `cli.getConfStanza()` has references on the following files (including line numbers):

```
wazuh-splunk/SplunkAppForWazuh/appserver/controllers/api.py
  512,22:             config = cli.getConfStanza("config", "configuration")

wazuh-splunk/SplunkAppForWazuh/appserver/controllers/manager.py
  90,19:             app = cli.getConfStanza(
  247,28:                 'version': cli.getConfStanza('app', 'launcher')['version'],
  248,29:                 'revision': cli.getConfStanza('app', 'install')['build'],
  249,35:                 'splunk_version': cli.getConfStanza('package', 'splunk')['version']
  730,27:             app_version = cli.getConfStanza('app', 'launcher')['version']

wazuh-splunk/SplunkAppForWazuh/appserver/controllers/report.py
  875,48:                                 docu_version = cli.getConfStanza('app', 'launcher')['version']

wazuh-splunk/SplunkAppForWazuh/bin/log.py
  88,22:             config = cli.getConfStanza("config", "configuration")

wazuh-splunk/SplunkAppForWazuh/bin/utils/config.py
  46,22:         apikeyconf = cli.getConfStanza(file, stanza)
```

## Proposed solution

These references need to be changed in order to ensure that the file to be read is under our App's scope.

We already make use of the `getLocalConfPath()` helper function, to read dynamic configurations, that are stored in the `$SPLUNK_HOME/etc/apps/SplunkAppForWazuh/local` directory. As the App configuration files are stored in the `$SPLUNK_HOME/etc/apps/SplunkAppForWazuh/default` directory, we will create a new helper function named `getDefaultConfPath()` as a clone of the existing function, slightly modifying the path as mentioned (replacing `local` with `default`).

The references identified before will then use this new function in order to have the absolute path to the files that they need to read.

https://github.com/wazuh/wazuh-splunk/blob/6594175eb9f18cee56f7aeb7a38f5c9cd800c8e7/SplunkAppForWazuh/bin/utils/config.py#L25-L33

**Comment by AlexRuiz7** [comment]
## Update

The new logic works as expected. I added new `DEBUG` logs in order to check that the correct files are indeed being read.

`/opt/splunk/var/log/splunk/SplunkAppForWazuh.log`
```
DEBUG: 2022/06/10 10:49:27: 'Reading "launcher" from /opt/splunk/etc/apps/SplunkAppForWazuh/default/app: {"version": "4.3.4", "author": "info@wazuh.com", "description": "Wazuh helps you to gain deeper security visibility into your infrastructure by monitoring hosts at an operating system and application level."}'
DEBUG: 2022/06/10 10:49:27: 'Reading "install" from /opt/splunk/etc/apps/SplunkAppForWazuh/default/app: {"build": "4307"}'
DEBUG: 2022/06/10 10:49:27: 'Reading "splunk" from /opt/splunk/etc/apps/SplunkAppForWazuh/default/package: {"version": "8.2.6"}'
```

To test this particular edge case, I installed several Apps randomly selected, including the "ES Content Updates". I could not find the Suricata App though.

New Wazuh APIs can be added without conflicts, as long as the App and API version match, only that this time it's guaranteed that the App's version to be read from the correct file.

![splunk_app_version](https://user-images.githubusercontent.com/15186973/173056483-38012446-1af6-4200-b0e1-884129d7445c.gif)

I'll continue with some clean up, documentation and standardization of the code, and then I'll open a new Pull Request with the fix, from which we can generate a new package.

**Comment by weekendwarrior1999** [comment]
That has appeared to work. It's reporting correctly now, and allowed me to add the Manager API details.

**Comment by AlexRuiz7** [comment]
Here, I provided instructions to build packages from source:

https://github.com/wazuh/wazuh-splunk/pull/1340#issuecomment-1163346792
