### ISSUE TITLE
wazuh app dashboard not work (because default SPL in cluster.name= )

### ISSUE THREAD

**Issue by k3igun** [wazuh/wazuh-splunk#1382]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.6   | 8.2.6     | 4309|

## Description
wazuh app dashboard not work (because default SPL in cluster.name= )

When configuring a cluster in wazuh , the default dashboard does not work. This is because the default SPL includes "cluster.name="

As shown in the figure below, if cluster.name=wazuh is included in the default SPL, splunk cant not search result
![image](https://user-images.githubusercontent.com/116377974/200330995-e2e159b4-071d-4142-a470-d320bce88a71.png)

However, remove "cluster.name=" from SPL, i can see search results as shown in the figure below.
![image](https://user-images.githubusercontent.com/116377974/200331054-a8a5d5f6-790f-40d1-8b9c-e443db83b992.png)

Is there any way to remove "cluster.name=" from the default SPL?

**Comment by AlexRuiz7** [comment]
Hello @k3igun 

By design, that's how the app works. That filter (`cluster.name=<wazuh_cluster_name>`) is included to fetch and show only the alerts that belong to the given cluster. Imagine you are monitoring several Wazuh clusters, `env_1` and `env_2`. Then, depending on the Wazuh cluster that is active (selected) in the Wazuh app, the dashboards will be built using the alerts that belong to that cluster.

The active environment can be quickly changed using the `Quick settings` dialog, and each environment can have an alias. Check on the images below how the filter changes depending on the selected environment (`wazuh1` and `wazuh2`, aliased to `env-1` and `env-2` respectively).

![image](https://user-images.githubusercontent.com/15186973/201629036-cdb1a24c-a3fa-4573-ac1e-26bc89023815.png)

![image](https://user-images.githubusercontent.com/15186973/201632314-81b9f85a-cc31-4b33-9200-a5ebced87049.png)

Note how the `cluster.name` filter changed, and also the data presented in the dashboard.

Now, if this is not working for you, it's very possible that there is a misconfiguration in your Wazuh cluster configuration somehow.

Are your alerts migrated from a different Wazuh environment?

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.
