### ISSUE TITLE
Option to view Agents across all API's 

### ISSUE THREAD

**Issue by atgithub11** [wazuh/wazuh-splunk#1495]
Hi,

Not sure if this has already been answered/addressed, but is there a way to view agent counts across all API's under Overview page. 

Right now, it only displays for the Wazuh API selected from Quick Settings dropdown. Having an "All" option in there would be great. (Similar to index/sourcetype dropdown)

<img width="216" alt="image" src="https://github.com/wazuh/wazuh-splunk/assets/20524313/ad0d5a84-1ed7-436a-99d2-13c87f7585cb">

**Comment by AlexRuiz7** [comment]
Hello @atgithub11 

There is no way to view all agents across APIs under the Overview page of the app. Each set of manager<>agents is managed and displayed independently by design, as each wazuh-manager is agnostic of other managers outside their cluster.

To get the total count of agents, you will need to manually count the agents connected to each manager.
