### ISSUE TITLE
Compatibility with Splunk 9.1.2

### ISSUE THREAD

**Issue by anastaceos** [wazuh/wazuh-splunk#1500]
## Description
HTML Dashboards are no longer supported in the version of Splunk Enterprise 9.1.2.

Currently, all Wazuh dashboards in the Wazuh Splunk app do not work.

**Comment by AlexRuiz7** [comment]
Hello @anastaceos 

Thank you for the heads-up.

We are aware of that, and for that reason (and many others) the app is no longer under development since Wazuh v4.6.0. Instead, we provide [integrations](https://documentation.wazuh.com/current/integrations-guide/splunk/index.html), which allows users to exploit the data gathered by Wazuh on Splunk (and other security solutions and platforms), while the configuration takes place on [Wazuh Dashboard](https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html).

The latest version of the Wazuh app for Splunk is [4.5.4](https://github.com/wazuh/wazuh-splunk/releases/tag/v4.5.4-8.2), which is compatible with Splunk 8.

For more information, read our [Splunk integration blog post](https://wazuh.com/blog/detection-with-splunk-integration/).
