### ISSUE TITLE
Splunk high load

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#403]
- [x] Research about index customization
- Test the next number of events along a week (modify OS date to achieve this task)
  - [x] 1.000 events
  - [x] 10.000 events
  - [x] 100.000 events
  - [x] 1.000.000 events
  - [ ] 10.000.000 events
  - [ ] 100.000.000 events
- [x] Research about node types, replication, cluster types...

**Comment by manuasir** [comment]
Generating events with the following command:


```
# change this 'size' variable
 size=$1
 while [ `wc -c /var/ossec/logs/alerts/alerts.json | cut -f1 -d ' '` -lt $size ]; do  
   cat /var/ossec/logs/alerts/alerts.json > /tmp/alerts.json && 
   cat /tmp/alerts.json >> /var/ossec/logs/alerts/alerts.json && 
   ll -h /var/ossec/logs/alerts/alerts.json;
done
```

Which appends alerts exponentially to the `alerts.json` file while its size is less than the selected size.

Testing the following number of events in a single Indexer without clustering:
  - [x] 1.000 events. No problems occured during the use of the app.
  - [x] 10.000 events. No problems occured during the use of the app.
  - [x] 100.000 events. No problems occured during the use of the app.
  - [x] 1.000.000 events. No problems occured during the use of the app.
  - [ ] 10.000.000 events
  - [ ] 100.000.000 events

Hardware specs:
```
Splunk Enterprise Server 7.2.1
Linux, 487 MB Physical Memory, 1 CPU Cores
Mode: Standalone
```

For 1M events, I had these performance results:
![image](https://user-images.githubusercontent.com/10210567/50086515-9cc4af00-01fd-11e9-9b2c-d4ab9f6d8f5c.png)

Additionally, I paste here the Splunk recommendations for troubleshooting with indexing actions.
![image](https://user-images.githubusercontent.com/10210567/50086404-39d31800-01fd-11e9-8d1a-50cfcb2493cd.png)

According to the Splunk [documentation](http://docs.splunk.com/Documentation/Splunk/7.2.1/Capacity/HowindexeddataaffectsSplunkEnterpriseperformance), changes depending on the size and amount of incoming data. Larger events slow down indexing performance. As events increase in size, the indexer uses more system memory to process and index them.
If you need more indexing capacity than a single indexer can provide, add indexers into the deployment to account for the increased demand.

### When should I scale my Splunk Enterprise deployment?

#### Question 1: Do you need to index more than 2GB of data per day?
#### Question 2: Do you need more than two users signed in at one time?
If you answer No to questions 1 and 2, then your Splunk platform instance can share a reference machine for distributed deployments with other Splunk platform services.

If you answer Yes to question 1 or 2, then proceed to Question 3.

Note When deploying Splunk Enterprise on Windows OS, do not utilize a host that provides Active Directory or Exchange services, or runs machine virtualization software. Those services are I/O intensive and can reduce Splunk Enterprise indexing and search performance.

#### Question 3: Do you need to index more than 300GB per day?
#### Question 4: Do you need more than four concurrent users?
If you answer No to questions 3 and 4, then a single dedicated Splunk Enterprise instance running on a reference machine can provide sufficient resources for the indexing and search workload. Go to Question 5.

If you answer Yes to question 3 or 4, then scale your Splunk Enterprise deployment to multiple machines to handle the increased demand of indexing and searching. Go to Question 5.

#### Question 5: Do you need more than 600GB of total storage?
See How Splunk Enterprise calculates disk storage.

If you answer No, then a single dedicated reference machine should be able to handle indexing and search workload, but you can consider adding additional storage to the machine to account for increased disk usage due to higher retention. Go to Question 6.

If you answer Yes, then scale your Splunk Enterprise deployment to multiple machines to handle the increased demand of indexing and searching. Go to Question 6.

#### Question 6: Do you want to create or run a Splunk app, alert, or solution that executes more than 8 concurrent saved searches?
#### Question 7: Do you need to search large quantities of data for a small set (less than 1 per cent) of results?
If you answer No to questions 6 and 7, you might not require multiple indexers in your Splunk Enterprise deployment at this time.

If you answer Yes to questions 6 or 7, then scale your Splunk Enterprise deployment to multiple machines to handle the increased demand of indexing and searching.

### Reference hardware
The reference hardware specification is a baseline for scoping and scaling the Splunk platform for your use. It is a performance guide for handling search and indexing loads.

Reference host specification for single-instance deployments
The following requirements represent the basic building block of a Splunk Enterprise deployment.
```
Intel x86 64-bit chip architecture
12 CPU cores at 2Ghz or greater speed per core
12GB RAM
Standard 1Gb Ethernet NIC, optional second NIC for a management network
Standard 64-bit Linux or Windows distribution
```

#### Disk subsystem
The disk subsystem for a reference machine should be capable of handling a high number of average Input/Output Operations Per Second (IOPS).

IOPS are a measurement of how much data throughput a hard drive can produce. Because a hard drive reads and writes at different speeds, there are IOPS numbers for disk reads and writes. The average IOPS is the blend between those two figures.

The more average IOPS that a hard drive can produce, the more data it can index and search in a given period of time. While many variable items factor into the amount of IOPS that a hard drive can produce, the following are the most important:

- Its rotational speed in revolutions per minute.
- Its average latency, which is the amount of time it takes to spin its platters half a rotation.
- Its average seek time, which is the amount of time it takes to retrieve a requested block of data.
The drives that are capable of producing the highest IOPS have high rotational speeds and low average latency and seek times. Every drive manufacturer provides this information, and some provide much more.

This specification uses eight 146GB, 15,000 RPM, serial-attached SCSI (SAS) HDs in a Redundant Array of Independent Disks (RAID) 1+0 fault tolerance scheme as the disk subsystem. Each hard drive is capable of about 200 average IOPS. The combined array produces a little over 800 average IOPS.

Insufficient disk I/O is the most common limitation in Splunk infrastructure. For the best results indexing your data, review the disk subsystem requirements before provisioning your hardware.

#### Maximum performance capability
The maximum performance capabilities measure indexing and search performance independently, and do not represent the combined load of a typical Splunk use case. To review performance recommendations for a reference machine with indexing with search load, see Summary of performance recommendations.

#### Indexing performance
- Up to 20MB per second (1700GB per day) of raw indexing performance if no searching or other index-related activity occurs.
Search performance
- Up to 50,000 events per second for dense searches.
- Up to 5,000 events per second for sparse searches.
- Up to 2 seconds per index bucket for super-sparse searches.
- From 10 to 50 buckets per second for rare searches with bloom filters.

### Reference host specification for distributed deployments
As the number of active users increases along with the data ingestion rate, the architecture requirements change from a single instance to a distributed Splunk Enterprise environment. The search head and indexer roles have unique hardware recommendations.

#### Dedicated search head
A search head uses CPU resources more consistently than an indexer, but does not require the fast disk throughput or a large pool of local storage for indexing.
```
Intel 64-bit chip architecture
16 CPU cores at 2Ghz or greater speed per core.
12GB RAM
2 x 300GB, 10,000 RPM SAS hard disks, configured in RAID 1
A 1Gb Ethernet NIC, optional 2nd NIC for a management network
A 64-bit Linux or Windows distribution
```
A search request uses up to 1 CPU core while the search is active. You must account for scheduled searches when you provision a search head in addition to ad-hoc searches that users run. More active users and higher concurrent search loads require additional CPU cores.

#### Indexer
When you distribute the indexing process, the Splunk platform can scale to consume terabytes of data in a day. When you add more indexers, you distribute the work of search requests and data indexing across those indexers. This increases performance significantly.

As a reminder, here is the reference indexer specification:

Reference host specification
```
Intel 64-bit chip architecture.
12 CPU cores at 2GHz or greater per core.
12GB RAM.
Disk subsystem capable of a minimum of 800 average IOPS.
A 1Gb Ethernet NIC, with optional second NIC for a management network.
A 64-bit Linux or Windows distribution.
```
Splunk has introduced two new specifications that help improve user experience by providing additional CPU cores for better indexing performance and search concurrency.

A single indexer carries the same disk I/O bandwidth requirements as a group of indexers.

#### Mid-range specification
The mid-range specification is similar to the base reference specification. This specification improves indexing capacity and search concurrency over a distributed Splunk Enterprise deployment.
```
Intel 64-bit chip architecture
24 CPU cores at 2GHz or greater speed per core
64GB RAM
Disk subsystem capable of a minimum of 800 average IOPS
A 1Gb Ethernet NIC, with optional second NIC for a management network
A 64-bit Linux or Windows distribution
```
#### High-performance specification
The high-performance specification is a further improvement upon the mid-range specification.
```
Intel 64-bit chip architecture
48 CPU cores at 2GHz or greater speed per core
128GB RAM
Disk subsystem capable of a minimum of 1200 average IOPS
A solid state disk (SSD) subsystem as a minimum requirement for hot and warm index buckets
A 1Gb Ethernet NIC with optional second NIC
A 64-bit Linux or Windows distribution
```
#### Disk subsystem information for higher-performance specifications
When indexers retrieve data for searches, they do many disk seeks and bulk reads. At higher daily volumes, local disk might not provide cost-effective storage for the time frames where you want a fast search. Fast attached storage or networked storage, such as storage area networks (SAN) over fiber, can provide the required IOPS for each indexer in these cases.

When you plan your storage infrastructure, understand these key points:

- More disks (specifically, more spindles) are better for indexing performance.
- Total throughput of the entire system is important.
- The ratio of disks to disk controllers in a particular system should be higher, similar to how you provision a database host.
- Ratio of indexers to search heads
There is no practical limitation on the number of search heads that an indexer can support, or on the number of indexers that a search head can search against. The use case determines what Splunk instance role (search head or indexer) the infrastructure needs to scale while maintaining performance. For a table with scaling guidelines, see Summary of performance recommendations.

#### Network latency limits for clustered deployments
A Splunk environment with search head or indexer clusters must have fast, low-latency network connectivity between clusters and cluster nodes. This is particularly important in environments that have clusters in multiple sites.

For indexer cluster nodes, network latency should not exceed 100 milliseconds. Higher latencies can significantly slow indexing performance and hinder recovery from cluster node failures.

### How Splunk Enterprise calculates disk storage
At a high level, Splunk calculates total disk storage as follows:

 `( Daily average indexing rate ) x ( retention policy ) x 1/2`

Splunk Enterprise stores raw data at up to approximately half its original size with compression. On a volume that contains 500GB of usable disk space, you can store nearly six months' worth of data at an indexing rate of 5GB/day or ten days' worth at a rate of 100GB/day.

If you need additional storage, you can opt for either more local disks, which is required for frequent searching, or you can use attached or network storage, which is acceptable for occasional searching. Low-latency connections over NFS or SMB/CIFS (Server Message Block/Common Internet File System) are acceptable for searches over long time periods where instant search returns can be compromised to lower cost per GB.

### Summary of performance recommendations
The Daily Indexing Volume table summarizes the performance recommendations that were given in the performance checklist. The table shows the number of reference machines that you need to index and search data in Splunk Enterprise, depending on the number of concurrent users and the amounts of data that the instance indexes.

An indexer that meets the reference hardware requirements can ingest up to 300GB/day while supporting a search load.

This table is only a guideline.
![image](https://user-images.githubusercontent.com/10210567/50088341-085d4b00-0203-11e9-9981-7d660c630689.png)

**Comment by manuasir** [comment]
Status: `stopped by license limitations`.
