### ISSUE TITLE
API configuration Remove credentials

### ISSUE THREAD

**Issue by kulozzzz** [wazuh/wazuh-splunk#47]
Hello:
I downloaded the wazzu-3.2.2-2.2.0.zip directly and unzipped it to $SPLUNK_HOME/etc/app/.
Edit the file inputs.conf:

```
[monitor:///var/ossec/logs/alerts/alerts.json]
disabled = 0
host = wazuhmanager
index = wazuh
sourcetype = wazuh
```
Edit the file and add the following stanza on props.conf. If it doesn't exist, create it:
```

[wazuh]
DATETIME_CONFIG = 
INDEXED_EXTRACTIONS = json
KV_MODE = none
NO_BINARY_CHECK = true
category = Application
disabled = false
pulldown_type = true

```
`$SPLUNK_HOME/bin/splunk restart`

After the restart is complete, go to WAZUH app prompt API configuration
Remove credentials.Is there any other configuration I haven't done yet?
![image](https://user-images.githubusercontent.com/29471339/39284083-2f6c741e-4944-11e8-8498-2c3cbbc8bff8.png)

**Comment by kulozzzz** [comment]
@manuasir 
hello
I have already done all of the above configuration, but when I click on the application, it will still appear above the figure
![image](https://user-images.githubusercontent.com/29471339/39341053-ed0d4d08-4a03-11e8-9c35-3af4b8d51c0a.png)

**Comment by kulozzzz** [comment]
@manuasir Is this related to my SPLUNK version? I use the 6.4.3 version of splunk

**Comment by manuasir** [comment]
Hi @kulozzzz ,

Sorry for the late response, unfortunately Wazuh app for Splunk works with greater than v6.6.x version of Splunk Enterprise. I'd recommend you to upgrade to the last version v7.1.0 in order to get the last improvings and fixes, maybe [this document](http://docs.splunk.com/Documentation/Splunk/7.1.0/Installation/AboutupgradingREADTHISFIRST) or [this other one](http://docs.splunk.com/Documentation/Splunk/7.1.0/Installation/InstallonLinux) could be interesting if you finally decide to upgrade. 
Also I will be happy to help you with the upgrading process if you need it.
Thank you for your patience and please,do not hesitate to open a new issue in the future.

Regards,
Manu

**Comment by kulozzzz** [comment]
@manuasir I updated our SPLUNK and successfully run wazzu-app, thanks

**Comment by manuasir** [comment]
Hi @kulozzzz ,

Nice to hear that. I'd like to thank you for report, the required version for the app will be included in our README. Please,don't hesitate to open a new issue if you need it and keep a close eye to the upcoming app release.

Regards, 
Manu
