### ISSUE TITLE
Add Discover sub-tab on every dashboard

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#512]
We want the same as Kibana app does.

![image](https://user-images.githubusercontent.com/8860227/51752016-a7088180-20b6-11e9-94cc-5d9b89627f44.png)

![image](https://user-images.githubusercontent.com/8860227/51752054-c1425f80-20b6-11e9-9598-08510b8292f7.png)

Main checks:

- [x] Discover/Dashboard switch button
- [x] Same search bar 
- [x] Same filters bar
- [x] Each section has its own filters
- [x] Pin filters
- [x] Remove pined agent filters when change to a agent state

Extra required checks:

- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists

**Comment by adri9valle** [comment]
Working on this branch => [3.9-discover-sub-tab](https://github.com/wazuh/wazuh-splunk/tree/3.9-discover-sub-tab)

**Comment by adri9valle** [comment]
- `Changed`: Discover button in the navbar open a clean search
- `Added`: Button in each section to open a custom discover
- `Added`: Button in the discover if come from the dashboard to back to it
- `Added`: Breadcrumbs in the discover if come from the dashboard

**Comment by adri9valle** [comment]
- `Changed`: Loading ring until then end of page charge
- `Changed`: Don't add focus to discover if come from a dashbboard
- `Added`: Discover button to all sections Overview/Agents
- `Fixed`: Some sections were showing  the `rule.group` filter but don't apply it to the discover, the filter is applied now when the discover app is opened
- `Changed`: Change how to remove a not implicit filter
- `Added`: Pin filters between sections
- `Fixed`: Remove pinned agent filters when change to a agent state

Comments:
- In the Discover of custom section, if a new filter is added, will be included when return to the dashboard, this is because in Splunk the filters are similar to a `SQL` query and you cannot distinct if you want make the filter pinned, implicit or not, then we will included the new filters always as normal filter.

- When access to a agent section the pinned filters that begin for `agent.` are removed because this could be create a conflict in a search, for example if a `agent.name` filter is pinned and this `agent.name` it's not the `agent.name` of the current `agent.id` the search will returns 0 results.

**Comment by adri9valle** [comment]
- `Added`: New filters writted in the discover will be applied when back to the dashboard
- `Fixed`: Prevent delete agent filters when access to an agent section from another agent section or the discover
