### ISSUE TITLE
Wazuh v3.2.2 and Splunk 7.1 API Configuration Page

### ISSUE THREAD

**Issue by suryjuto** [wazuh/wazuh-splunk#59]
API configuration page is blank

![image](https://user-images.githubusercontent.com/24494768/39932093-34d326ee-550d-11e8-889c-87febda3c605.png)

This is occurring with both the Splunkbase version and the Github version.

**Comment by manuasir** [comment]
hI @suryjuto ,

The last released app v3.2.2 id supported by the latest Splunk Enterprise v7.1, could you please tell me which Splunk Enterprise version are you running? You can easilly check it by navigating to 'Help' upper right section and clicking on 'About' subtab, please copy and paste here the version tag.

Regards,
Manu

**Comment by suryjuto** [comment]
Hi again, Manu!


Splunk EnterpriseVersion:7.1.0Build:2e75b3406c5b

**Comment by manuasir** [comment]
Hello @suryjuto ,

Your problem was related to a bug that has been already fixed thanks to your report. Due to legacy with the Splunkbase package, we had to keep the old app v1.0 app name so that now the root folder is named 'SplunkAppForWazuh'. This change crashed the app down and generates a few unwanted things so please, follow these steps in your system:

1. Download the last package with the fix [here](https://github.com/wazuh/wazuh-splunk/releases/download/v3.2.0/v3.2.0-7.1.0.tar.gz)

2. Remove the old 'wazuh' app in your Splunk directory:
```
# rm $SPLUNK_HOME/etc/apps/wazuh/ -rf
```
Also if exists, remove the 'SplunkAppForWazuh' app folder:
```
# rm $SPLUNK_HOME/etc/apps/SplunkAppForWazuh/ -rf
```
3. Install the new app:

 ```
$SPLUNK_HOME/bin/splunk install app v3.2.0-7.1.0.tgz
```
4. Restart Splunk service:
```
$SPLUNK_HOME/bin/splunk restart
```
Sorry for the inconvenience and please let me know if everything went alright.

Regards,
Manu

**Comment by manuasir** [comment]
Hi @suryjuto ,

I'm glad to hear everything was fixed,thank you for your feedback.
Please don't hesitate to open a new issue whenever you need it, I will be pleased to help with it

Regards,
Manu
