### ISSUE TITLE
Agents > Inventory several improvements

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#744]
| Wazuh | Splunk | Rev |
|-----------|----------|-------|
|  3.9/3.10      |  7.x      | 28 |

**Description**
In Agents > Inventory there are several things to improve.

- [x] There's a flick when accessing to the section
- [x] The tables are not distributed as Kibana
- [x] Missing cursor pointer in the sort icons

**Screenshots**

![flick_ag_inv](https://user-images.githubusercontent.com/7983984/59030277-dac39700-8860-11e9-88d7-365361c9d13c.gif)

**Comment by adri9valle** [comment]
**Update** 

I've set the same disposition that Kibana has:

![image](https://user-images.githubusercontent.com/7983984/59031081-05165400-8863-11e9-979e-e1fcb16b2c9e.png)

**Comment by adri9valle** [comment]
**Update**

Solved problem with the missing cursor pointers https://github.com/wazuh/wazuh-splunk/commit/d3aa59f7c24b4d3696b74b907b44e34399aedb1b

**Comment by adri9valle** [comment]
**Update**

Solved problem with the flick when accessing to Agents > Inventory:

![flck_solved](https://user-images.githubusercontent.com/7983984/59040438-f3d74280-8876-11e9-902f-b86c46918fff.gif)

**Comment by pablotr9** [comment]
**Update**
Instead of making an api query for every syscollector item, it has been added a new single backend route to obtain syscollector basic information https://github.com/wazuh/wazuh-splunk/commit/dd12386b8295e2462e62451d03a37d7a9eefe0ba and the controller has been adapted to use this new backend route https://github.com/wazuh/wazuh-splunk/commit/e394713bcea157676da1c6f3af82409ffc6e47e0. 
There was found an error with our backend method `get_credentials`, it has been fixed too.
It has been added last scan informatoin of syscollector and it has also been adapted for MacOs agents.https://github.com/wazuh/wazuh-splunk/commit/fd5d1870c90a32311710abc226c57c84074d2b61

![image](https://user-images.githubusercontent.com/35685689/59755822-e5325780-9288-11e9-99f8-cc99dafab137.png)

**Comment by pablotr9** [comment]
**Update**
Testing the inventory table with a MacOS Agent, following errors have been found and fixed here https://github.com/wazuh/wazuh-splunk/commit/c55f149c605fb7e65dc45aa8795d4802b704046a:
  - Removed both _ports_ and _processes_ tables (that information is missing for MacOS until 3.11)
  - Changed the _packages_ table, it was showing two empty columns always and missing two more columns. Now, this is how it looks for MacOS agents:
![Untitled Diagram (6)](https://user-images.githubusercontent.com/35685689/59904809-c6f16680-9404-11e9-8937-aabac71ee570.png)
