### ISSUE TITLE
Missing indexes.conf

### ISSUE THREAD

**Issue by rakanskiy** [wazuh/wazuh-splunk#751]
| Wazuh | Splunk | Rev |
|-----------|----------|-------|
|  3.9.1     |  7.3.0      | N/A |

**Description**
App from version 3.9.0_7.2.6 to current 3.9.1_7.3.0 missed indexes.conf

**Steps to reproduce**
1. Install/upgrade app
2. Restart Splunk
3. Receive don`t working app and messages from Splunk 

**Screenshots**
![image](https://user-images.githubusercontent.com/30781071/59187274-c55ead80-8b7d-11e9-98dd-155f9646de71.png)
![image](https://user-images.githubusercontent.com/30781071/59187279-cb548e80-8b7d-11e9-9dfb-3bbb2908e16e.png)

**Additional context**
With indexed.conf from 3.8.2_7.2.5 works well.

**Comment by adri9valle** [comment]
Hi @rakanskiy 

The **indexes.conf** content from `3.8.2_7.2.5` has not changed, but the way to configure it in Splunk yes.

In the `3.8.x` version, the App contains the **indexes.conf** this makes that the App create the indexes automatically. Since the `3.9.x` version the **indexes.conf** file must be created in `/opt/splunk/etc/system/local`  in order to Splunk creates the indexes. 

In order to give you better assistance, please ask me the following questions:

- Did you have `/opt/splunk/etc/system/local/indexes.conf` created when Splunk threw this error ?
- To solve this, where did you copy the **indexes.conf** from `3.8.2_7.2.5`?

I hope this clarifies the problem. I'm waiting for your response in order to know the reason why this problem happened. 

Regards,

**Comment by rakanskiy** [comment]
- No, I don`t have ```/opt/splunk/etc/system/local/indexes.conf```
- Yes, I`ve copied it to ```defaut``` directory inside app

**Comment by adri9valle** [comment]
Hi @rakanskiy,

There's the problem. If you came from `3.9.0_7.2.6` to `3.9.1_7.3.0` and you didn't have `/opt/splunk/etc/system/local/indexes.conf` created Splunk wont create the indexes.

On the other hand, I advise you that you should move the **indexes.conf** from the `default` directory inside the app to `/opt/splunk/etc/system/local` because if you delete the App or update it you'll have the same problem again.

Please, could you say me if you remember it how did you configure the **indexes.conf** in `3.9.0_7.2.6` version? Because by default the file is not present in this version, maybe you configured it in the `default` directory in the App this could explain this problem.

Regards,

**Comment by rakanskiy** [comment]
I`ve handle it the same way, by copying indexes.conf from ```3.8.2_7.2.5```

**Comment by rakanskiy** [comment]
Please consider to update documentation regarding changes in 3.9.x version

**Comment by adri9valle** [comment]
Hi @rakanskiy,

This explains your problem, as I said if you copied the **indexed.conf** inside the App when you update the App the indexes will disappear. Please to prevent this move the **indexes.conf** to `/opt/splunk/etc/system/local`. Thanks.

> Please consider to update documentation regarding changes in 3.9.x version

Of course, here is the issue https://github.com/wazuh/wazuh-documentation/issues/1270 you can track it and I'm already working on it

Regards,

Adri,

**Comment by rakanskiy** [comment]
Thanks!
