### ISSUE TITLE
Do not show unsupported modules in agents depending on the OS

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-splunk#753]
| Wazuh | Splunk | Rev |
|-----------|----------|--------|
|  3.x      |  7.3      |  n/a  |

**Description**
Some sections such as the welcome screen of an agent and its configuration are showing unsupported modules. Our community might think that a Windows agent can use Vulnerability detector for example (it will, but not so far)

**Steps to reproduce**
1. Go to "Agents"
2. Click on an agent that is not a Linux agent

**Screenshots**
For example, for a Windows agent:

![image](https://user-images.githubusercontent.com/8860227/59205201-b6d6bd00-8ba2-11e9-9c78-3f07a361b60b.png)

**Proposal**

Properly filter modules and their related configuration depending on the agent OS.

**Comment by adri9valle** [comment]
Hi team, 

There's the list of supported "modules" from the different OS:

- Linux: OpenScap, Audit, Vulnerabilites and Docker.


**NOTES**: 
- Whodata is supported by Windows too, but the method is different that's why Audit is not enabled in Windows.
- Vulnerability detection actually only supports RedHat/Centos, Debian, Ubuntu, and Amazon Linux, this means that is only enabled for Linux agents.
- Docker is only supported by Linux natively, that's why `docker-listener` module is only for Linux now.

The rest of the modules are supported by all OS if some module is not enabled only need to configure it following our official documentation: [Wazuh documentation](https://documentation.wazuh.com/current/index.html)

To solve this I propose to check the agent OS platform (Linux, Windows, Mac) in the controller and check in the view if the agent must be content the module card, for example:

##### Controller:
```
this.scope.isLinux = this.agent[0].data.data.os.uname.includes(
              'Linux'
            )
this.scope.isWindows = this.agent[0].data.data.os.uname.includes(
              'Microsoft'
            )
 this.scope.isMac = this.agent[0].data.data.os.uname.includes(
              'osx'
            )
```

##### View:

```
<wz-welcome-card ng-if="isLinux"...
```


Regards,

**Comment by pablotr9** [comment]
**Update**
When any of the cards has no available extensions insted of showing an empty card we now show the following info message: https://github.com/wazuh/wazuh-splunk/commit/f544ed749125661628121723f861689a6b82bbd9

![image](https://user-images.githubusercontent.com/35685689/59337905-b3a61300-8d01-11e9-9d01-d6d5f6758fbb.png)

**Comment by adri9valle** [comment]
**Update**

I've changed the logic with we check the OS platform of the agent, now we have a JSON:

```
this.excludeModulesByOs = {
        'linux': [],
        'windows': ['audit', 'oscap', 'vuls', 'docker'],
        'darwin': ['audit', 'oscap', 'vuls', 'docker'],
        'other': ['audit', 'oscap', 'vuls', 'docker']
      }
```
And then once the agents platform is detected the modules are checked with this JSON in order to show or hide them.

Regards,

**Comment by pablotr9** [comment]
**Update**
- All raw SVG have been replaced with our directive `<wz-svg icon="x">` instead of using the same raw SVG in different places.
- There was a typo using `darwing` instead of `darwin`: Fixed
- In a specific agent with status `Never Connected` we were getting this error: 
![image](https://user-images.githubusercontent.com/35685689/60024112-7c3b4d00-9697-11e9-9b1d-bee9bd664442.png)
This have been fixed by correctly checking the agent platform.
- Also when accessing Configuration of a Never Connected agent, we were getting these 2 errors, 
![screenshot-flameshot-2019-06-2414_2](https://user-images.githubusercontent.com/35685689/60024238-bc9acb00-9697-11e9-8bdb-8f890d1621a0.png)
Both empty box and unexpected error message have been fixed
