### ISSUE TITLE
Error in the agent table in environments more than 100k agents

### ISSUE THREAD

**Issue by jsanchez91** [wazuh/wazuh-splunk#941]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.13.x   | 8.0.2     | 444 |

**Description**
A user reports an error in the agent table when working in environments of more than 100k agents.

This can be due to the fact that pagination is not done using the API parameters.

```
Error while init table. Maximum call stack size exceeded
```

**Comment by MiguelCasaresRobles** [comment]
Hello team,

In addition to this, the error seems to be raised when calling a recursive function in a loop. It may occur when there is an infinite loop or when a function is called which in turn calls another function and so forth until you hit the call stack limit.

I’ve checked the Wazuh Splunk add-on code and found two different parts of it that can be related to this:

https://github.com/wazuh/wazuh-splunk/blob/v3.13.2-8.0.4/SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js#L405

https://github.com/wazuh/wazuh-splunk/blob/v3.13.2-8.0.4/SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/init.js#L60

Regards,

Miguel Casares

**Comment by asteriscos** [comment]
Hi team,

after analyzing this issue I noticed there are actually several problems with the agents table. 
Just to mention a few things:
When it initializes the table it makes an agent request obtaining the maximum amount of records the API allows (500) and then divides the rows into pages (instead of making a request just for the page size)
For this reason, **one won't be able to see more than 500 agents in the table**, even though there could be several thousands. 

There are also other issues with the pagination system, so the best way to solve this is to refactor it.

![image](https://user-images.githubusercontent.com/9343732/114889788-ca778e00-9de0-11eb-9a36-ba51294f7d6b.png)

![image](https://user-images.githubusercontent.com/9343732/114890189-2d692500-9de1-11eb-8ef7-b84d16e0441e.png)

![image](https://user-images.githubusercontent.com/9343732/114890585-8638bd80-9de1-11eb-8be9-129b9dc16fcf.png)

The table will be redesigned to properly handle pagination and optimizing server side resources.
